/*

Filename: game_tiles_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 16 x 11
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define game_tiles_map_width 16
#define game_tiles_map_height 11
#define game_tiles_map_tiles 176
#define game_tiles_map_bytes 176

extern unsigned char game_tiles_map[];
extern unsigned char game_tiles_map_attr[];

