/*

 MenuMap.h

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : ./res/MenuMap.tmx
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by tiled-to-map 1.0.0 on Wed Mar 20 2024 22:58:38 GMT-0300 (Brasilia Standard Time)

*/

#ifndef MENUMAP__INCLUDE
#define MENUMAP__INCLUDE

#define MenuMap_WIDTH  20
#define MenuMap_HEIGHT 18

extern const unsigned char MenuMap_TILES[];

#endif /* MENUMAP__INCLUDE */
