/*

 CreditsMap.h

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : ./res/CreditsMap.tmx
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by tiled-to-map 1.0.0 on Wed Mar 27 2024 17:51:58 GMT-0300 (Brasilia Standard Time)

*/

#ifndef CREDITSMAP__INCLUDE
#define CREDITSMAP__INCLUDE

#define CreditsMap_WIDTH  20
#define CreditsMap_HEIGHT 18

extern const unsigned char CreditsMap_TILES[];

#endif /* CREDITSMAP__INCLUDE */
