/*

 HudWin.c

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : ./res/HudWin.tmx
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by tiled-to-map 1.0.0 on Wed Mar 27 2024 17:51:58 GMT-0300 (Brasilia Standard Time)

*/


#define HudWin_WIDTH  20
#define HudWin_HEIGHT 2

const unsigned char HudWin_TILES[] =
{
     152, 154,   6,   7, 157, 154, 158,   8,   9, 157, 154, 158,  -1,  10,  11, 154, 154, 154, 154, 153,
     155,  -1,  22,  23,  -1,  -1,  -1,  24,  25,  -1,  -1,  -1,  -1,  12,  13,  -1,  -1,  -1,  -1, 156,
};
