/*

 HudWin.h

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : ./res/HudWin.tmx
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by tiled-to-map 1.0.0 on Wed Mar 27 2024 17:51:58 GMT-0300 (Brasilia Standard Time)

*/

#ifndef HUDWIN__INCLUDE
#define HUDWIN__INCLUDE

#define HudWin_WIDTH  20
#define HudWin_HEIGHT 2

extern const unsigned char HudWin_TILES[];

#endif /* HUDWIN__INCLUDE */
